# Generated by Django 4.2 on 2024-12-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signupmodel',
        ),
    ]
