# Generated by Django 4.2 on 2024-12-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_signup_signupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiree',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
