# Generated by Django 4.2 on 2024-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_workers_delete_add_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('job_title', models.TextField()),
                ('work_location', models.TextField()),
                ('job_requirements', models.CharField(max_length=500)),
            ],
        ),
    ]
