# Generated by Django 4.2 on 2024-12-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_job',
            new_name='add_jobmodel',
        ),
    ]
