# Generated by Django 4.2 on 2024-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='addjob_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('job_title', models.TextField()),
                ('work_location', models.TextField()),
                ('job_requirements', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='add_jobmodel',
        ),
    ]
