# Generated by Django 4.2 on 2024-12-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_addjob_model_delete_add_jobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='addworker_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('skills', models.TextField()),
                ('exp', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='add_workers',
        ),
    ]
