# Generated by Django 4.2 on 2024-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_addworker_model_delete_add_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
